# Generated by Django 4.0.1 on 2022-11-01 22:19

import ckeditor.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ انتشار')),
                ('title', models.CharField(help_text='متن منحصر به فرد باید باشد', max_length=128, unique_for_month='published_at', verbose_name='متن')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=1, verbose_name='وضعیت')),
                ('summary', models.CharField(max_length=128, verbose_name='خلاصه')),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='پیام')),
            ],
            options={
                'verbose_name': 'تیم',
                'verbose_name_plural': 'تیم ما',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ انتشار')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=1, verbose_name='وضعیت')),
                ('first_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='نام')),
                ('last_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='نام خانوادگی')),
                ('role', models.CharField(blank=True, max_length=128, null=True, verbose_name='سمت')),
                ('phone', models.CharField(blank=True, max_length=128, null=True, verbose_name='تلفن')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='memnber/%Y/%m/%d')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='اینستاگرام')),
                ('whatsapp', models.URLField(blank=True, null=True, verbose_name='واتس آپ')),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='لینکدین')),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='پیام')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team', to='team.team')),
            ],
            options={
                'verbose_name': 'عضو',
                'verbose_name_plural': 'اعضاًٰٰ\u200c',
            },
        ),
    ]
