# Generated by Django 4.0.1 on 2023-01-09 20:04

from django.db import migrations, models

import painless.models.validations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerfeedback',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='feedback/%Y/%m/%d', validators=[painless.models.validations.validate_file_extension, painless.models.validations.validate_file_size], verbose_name='تصویر'),
        ),
    ]
