# Generated by Django 4.0.1 on 2022-09-13 09:28

from django.db import migrations, models

import painless.models.validations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=12, validators=[painless.models.validations.validate_charachters], verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=12, validators=[painless.models.validations.validate_charachters], verbose_name='نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(max_length=12, validators=[painless.models.validations.validate_phone_number], verbose_name='موبایل'),
        ),
    ]
