# Generated by Django 4.0.1 on 2023-04-28 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, editable=False, max_length=125, null=True),
        ),
    ]
