# Generated by Django 4.0.1 on 2023-01-09 20:04

from django.db import migrations, models

import painless.models.validations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='banner',
            field=models.ImageField(blank=True, upload_to='category/%Y/%m/%d', validators=[painless.models.validations.validate_file_extension, painless.models.validations.validate_file_size], verbose_name='تصویر'),
        ),
    ]
