# Generated by Django 4.0.1 on 2022-08-30 14:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ انتشار')),
                ('title', models.CharField(help_text='متن منحصر به فرد باید باشد', max_length=128, unique_for_month='published_at', verbose_name='متن')),
                ('slug', models.CharField(max_length=128, unique_for_month='published_at', verbose_name='اسلاگ')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=1, verbose_name='وضعیت')),
            ],
            options={
                'verbose_name': 'برچسب',
                'verbose_name_plural': 'برچسبها',
                'ordering': ['-created'],
            },
        ),
    ]
