# Generated by Django 4.0.1 on 2022-11-18 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['-title'], 'verbose_name': 'برچسب', 'verbose_name_plural': 'برچسبها'},
        ),
    ]
