# Generated by Django 4.0.1 on 2023-04-26 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='token',
            field=models.CharField(blank=True, editable=False, max_length=32, null=True),
        ),
    ]
