# Generated by Django 4.0.1 on 2023-05-05 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_ipaddress_remove_user_token'),
        ('blog', '0004_remove_post_token_post_viewers'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hits',
            field=models.ManyToManyField(blank=True, related_name='hits', to='accounts.IPAddress', verbose_name='بازدیدهای یونیک'),
        ),
    ]
