# Generated by Django 4.0.1 on 2023-05-05 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_post_hits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='viewers',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
