# Generated by Django 4.0.1 on 2022-12-10 20:27

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import painless.models.validations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Renewal',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ انتشار')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=64, null=True, verbose_name='نام بیمه گذار')),
                ('phone', models.CharField(max_length=128, validators=[painless.models.validations.validate_phone_number], verbose_name='تلفن')),
                ('code', models.CharField(blank=True, max_length=128, null=True, verbose_name='کد رهگیری')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cats', to='category.category')),
            ],
            options={
                'verbose_name': 'تمدید',
                'verbose_name_plural': 'تمدیدی',
                'ordering': ['-published_at', 'name'],
                'get_latest_by': ['-published_at'],
            },
        ),
    ]
