# Generated by Django 4.0.1 on 2023-01-12 09:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='broadcastnotification',
            options={'ordering': ['-published_at'], 'verbose_name': 'نوتیفیکیشن', 'verbose_name_plural': 'نوتیفیکیشنها'},
        ),
        migrations.RemoveField(
            model_name='broadcastnotification',
            name='broadcast_on',
        ),
        migrations.AddField(
            model_name='broadcastnotification',
            name='published_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ انتشار'),
        ),
        migrations.AlterField(
            model_name='broadcastnotification',
            name='message',
            field=models.TextField(verbose_name='پیام'),
        ),
        migrations.AlterField(
            model_name='broadcastnotification',
            name='sent',
            field=models.BooleanField(default=False, verbose_name='وضعیت انتشار'),
        ),
    ]
